# __Confidence Interval Estimate using 1 Sample (if population std is known)__

In [1]:
import pandas as pd
import numpy as np

from scipy import stats

In [3]:
population_df = pd.read_csv('adult.csv')

population_df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
# Step 1: Take a sample (Large enough)
sample_size = 200

sample_df = population_df.sample(n=sample_size, random_state=0)

In [5]:
sample_df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
38113,36,Private,65624,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,<=50K
39214,57,Self-emp-inc,37345,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,36,United-States,>50K
44248,49,Private,287647,Masters,14,Divorced,Sales,Not-in-family,White,Male,4787,0,45,United-States,>50K
10283,54,Self-emp-not-inc,183668,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,55,United-States,<=50K
26724,17,Self-emp-not-inc,228786,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39532,38,Private,391040,Assoc-voc,11,Separated,Tech-support,Unmarried,White,Female,0,0,20,United-States,<=50K
21442,32,Private,194987,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,Black,Female,0,0,40,United-States,<=50K
28011,30,Private,447739,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States,<=50K
32094,32,Federal-gov,42900,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,50,United-States,>50K
6450,32,Private,453983,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,44,United-States,<=50K

In [6]:
# Step 2: Calculate sample statistics (i.e. mean and standard deviation of the sample)

population_std = np.std(population_df['age'])
sample_mean = np.mean(sample_df['age'])
sample_std = np.std(sample_df['age'], ddof=1)

# Use ddof=1 for sample standard deviation
# The divisor used in calculations is N - ddof, where N represents the number of elements.
# By default ddof is zero.

print("Population Std:", population_std)
print("Sample Mean:", sample_mean)
print("Sample Std:", sample_std)

Population Std: 13.710369577986553
Sample Mean: 38.94
Sample Std: 13.512934432791598

In [7]:
# Step 3: Set confidence level (e.g., 95% confidence level)
confidence_level = 0.95

In [8]:
# Step 3a: Calculate standard error (SE)
standard_error = population_std / np.sqrt(sample_size)

print("Standard Error:", standard_error)

Standard Error: 0.9694695301168035

In [9]:
# Step 3b: Calculate the critical value (z-score)
significance_level = 1 - confidence_level

z_score = stats.norm.ppf(1 - significance_level/2) # Considering it to be a two tail test
# ppf ---> percent point function

print("Z Score:", z_score)

Z Score: 1.959963984540054

In [10]:
# Step 3c: Calculate the margin of error (MOE)
margin_of_error = z_score * standard_error

print("Margin of Error:", margin_of_error)

Margin of Error: 1.900125363137904

In [11]:
# Step 4: Calculate the confidence interval
lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Lower Bound: 37.039874636862095
Upper Bound: 40.8401253631379

In [12]:
# Print the results
print(f"Sample Mean: {sample_mean}")
print(f"Margin of Error: {margin_of_error}")
print(f"Confidence Interval ({confidence_level*100}%): ({lower_bound}, {upper_bound})")

print()
print("R E S U L T")
print(f"Population mean is estimated to lie in ({lower_bound}, {upper_bound}) range with {confidence_level*100}% confidence.")

Sample Mean: 38.94
Margin of Error: 1.900125363137904
Confidence Interval (95.0%): (37.039874636862095, 40.8401253631379)

R E S U L T
Population mean is estimated to lie in (37.039874636862095, 40.8401253631379) range with 95.0% confidence.

# __Confidence Interval Estimate using 1 Sample (if Population Std is unknown)__

In [13]:
# Step 1: Take a sample (Large enough)
sample_size = 200

sample_df = population_df.sample(n=sample_size, random_state=0)

In [14]:
# Step 2: Calculate sample statistics (i.e. mean and standard deviation of the sample)

population_std = np.std(population_df['age'])
sample_mean = np.mean(sample_df['age'])
sample_std = np.std(sample_df['age'], ddof=1)

# Use ddof=1 for sample standard deviation
# The divisor used in calculations is N - ddof, where N represents the number of elements.
# By default ddof is zero.

print("Population Std:", population_std)
print("Sample Mean:", sample_mean)
print("Sample Std:", sample_std)

Population Std: 13.710369577986553
Sample Mean: 38.94
Sample Std: 13.512934432791598

In [15]:
# Step 3: Set confidence level (e.g., 95% confidence level)
confidence_level = 0.95

In [16]:
# Step 3a: Calculate standard error (SE)
standard_error = sample_std / np.sqrt(sample_size)

print("Standard Error:", standard_error)

Standard Error: 0.9555087571156131

In [17]:
# Step 3b: Calculate the critical value (t-value )
significance_level = 1 - confidence_level

t_score = stats.t.ppf(1 - significance_level/2, df=sample_size-1)

print("t Score:", t_score)

t Score: 1.971956544249395

In [18]:
# Step 3c: Calculate the margin of error (MOE)
margin_of_error = t_score * standard_error

print("Margin of Error:", margin_of_error)

Margin of Error: 1.8842217466817388

In [19]:
# Step 4: Calculate the confidence interval
lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Lower Bound: 37.05577825331826
Upper Bound: 40.82422174668174

In [20]:
# Print the results
print(f"Sample Mean: {sample_mean}")
print(f"Margin of Error: {margin_of_error}")
print(f"Confidence Interval ({confidence_level*100}%): ({lower_bound}, {upper_bound})")

print()
print("R E S U L T")
print(f"Population mean lies in ({lower_bound}, {upper_bound}) range with {confidence_level*100}% confidence.")

Sample Mean: 38.94
Margin of Error: 1.8842217466817388
Confidence Interval (95.0%): (37.05577825331826, 40.82422174668174)

R E S U L T
Population mean lies in (37.05577825331826, 40.82422174668174) range with 95.0% confidence.