In [1]:
import pandas as pd

## New Topic Classification

In [2]:
train_df = pd.read_csv('/content/drive/MyDrive/MLDatasets/text_classification/train_10k.csv',names=['label','heading','text'])
train_df.head()

,label,heading,text
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

In [3]:
train_df.label.value_counts()

label
3    10000
4    10000
2    10000
1    10000
Name: count, dtype: int64

In [4]:
label_encoding = {'1':'world','2':'sports','3':'business','4':'science_tech'}

## Build the vocabulary

In [7]:
import re
_token_reg = re.compile(r"[a-z0-9]+")
# this regex will tokenize the text into alphanumeric tokens


def tokenize(text):
  text=text.lower()
  tokens = _token_reg.findall(text)
  return tokens

In [9]:
print(train_df.iloc[0].text)

tokens = tokenize(train_df.iloc[0].text)
print(tokens)

Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.
['reuters', 'short', 'sellers', 'wall', 'street', 's', 'dwindling', 'band', 'of', 'ultra', 'cynics', 'are', 'seeing', 'green', 'again']

In [10]:
from collections import Counter

def build_vocab(texts,max_size=50000):
  counter = Counter()
  for text in texts:
    tokens = tokenize(text)
    counter.update(tokens)

  return counter

# counter takes all tokens of corpus as input and computes their frequencies
# it counts how many times a given token has appeared in given corpus

In [11]:
counter = build_vocab(train_df['text'].to_list())

In [ ]:
counter

Counter({'reuters': 5703,
         'short': 236,
         'sellers': 15,
         'wall': 421,
         'street': 491,
         's': 17102,
         'dwindling': 12,
         'band': 48,
         'of': 30335,
         'ultra': 22,
         'cynics': 2,
         'are': 3054,
         'seeing': 39,
         'green': 182,
         'again': 332,
         'private': 186,
         'investment': 282,
         'firm': 514,
         'carlyle': 1,
         'group': 1361,
         'which': 1559,
         'has': 5881,
         'a': 36275,
         'reputation': 35,
         'for': 12770,
         'making': 404,
         'well': 388,
         'timed': 9,
         'and': 22575,
         'occasionally': 5,
         'controversial': 124,
         'plays': 48,
         'in': 27057,
         'the': 66859,
         'defense': 286,
         'industry': 613,
         'quietly': 39,
         'placed': 80,
         'its': 7182,
         'bets': 8,
         'on': 16223,
         'another': 714,
         'part': 504,
         'market': 1066,
         'soaring': 72,
         'crude': 406,
         'prices': 1451,
         'plus': 136,
         'worries': 135,
         'about': 2029,
         'economy': 488,
         'outlook': 167,
         'earnings': 475,
         'expected': 802,
         'to': 32714,
         'hang': 13,
         'over': 3055,
         'stock': 577,
         'next': 1088,
         'week': 1908,
         'during': 660,
         'depth': 30,
         'summer': 252,
         'doldrums': 9,
         'authorities': 274,
         'have': 3532,
         'halted': 19,
         'oil': 1889,
         'export': 37,
         'flows': 13,
         'from': 5428,
         'main': 223,
         'pipeline': 78,
         'southern': 371,
         'iraq': 1493,
         'after': 4244,
         'intelligence': 169,
         'showed': 351,
         'rebel': 238,
         'militia': 134,
         'could': 1418,
         'strike': 263,
         'infrastructure': 67,
         'an': 5657,
         'official': 584,
         'said': 6761,
         'saturday': 1369,
         'afp': 812,
         'tearaway': 1,
         'world': 2253,
         'toppling': 13,
         'records': 95,
         'straining': 12,
         'wallets': 10,
         'present': 49,
         'new': 6034,
         'economic': 480,
         'menace': 5,
         'barely': 65,
         'three': 1959,
         'months': 663,
         'before': 868,
         'us': 3131,
         'presidential': 327,
         'elections': 217,
         'stocks': 1294,
         'ended': 322,
         'slightly': 126,
         'higher': 556,
         'friday': 2221,
         'but': 2899,
         'stayed': 30,
         'near': 462,
         'lows': 40,
         'year': 2764,
         'as': 7393,
         'surged': 88,
         'past': 478,
         '36': 402,
         '46': 75,
         'barrel': 262,
         'offsetting': 8,
         'positive': 108,
         'computer': 816,
         'maker': 724,
         'dell': 83,
         'inc': 2305,
         'o': 634,
         'ap': 3014,
         'assets': 82,
         'nation': 461,
         'retail': 186,
         'money': 326,
         'mutual': 143,
         'funds': 177,
         'fell': 473,
         'by': 6385,
         '1': 1995,
         '17': 367,
         'billion': 962,
         'latest': 555,
         '849': 1,
         '98': 18,
         'trillion': 27,
         'company': 2472,
         'institute': 58,
         'thursday': 2447,
         'usatoday': 48,
         'com': 1299,
         'sales': 822,
         'bounced': 21,
         'back': 1079,
         'bit': 116,
         'july': 305,
         'claims': 217,
         'jobless': 43,
         'benefits': 127,
         'last': 2113,
         'government': 1546,
         'indicating': 27,
         'is': 6460,
         'improving': 80,
         'midsummer': 4,
         'slump': 32,
         'forbes': 57,
         'earning': 11,
         'ph': 2,
         'd': 175,
         'sociology': 1,
         'danny': 28,
         'bazil': 1,
         'riley': 16,
         'started': 173,
         'work': 484,
         'general': 491,
         'manager': 309,
         'at': 7139,
         'commercial': 146,
         'real': 267,
         'estate': 54,
         'annual': 229,
         'base': 133,
         'salary': 15,
         '70': 98,
         '000': 886,
         'soon': 255,
         'financial': 536,
         'planner': 5,
         'stopped': 78,
         'his': 4911,
         'desk': 28,
         'drop': 232,
         'off': 1238,
         'brochures': 1,
         'insurance': 110,
         'available': 187,
         'through': 717,
         'employer': 13,
         '32': 76,
         'buying': 113,
         'was': 4540,
         'furthest': 2,
         'thing': 80,
         'my': 121,
         'mind': 60,
         'says': 986,
         'york': 2324,
         'tehran': 116,
         'opec': 128,
         'can': 1067,
         'do': 460,
         'nothing': 101,
         'douse': 2,
         'scorching': 9,
         'when': 1721,
         'markets': 255,
         'already': 265,
         'oversupplied': 1,
         '2': 1884,
         '8': 572,
         'million': 1648,
         'barrels': 55,
         'per': 377,
         'day': 1303,
         'bpd': 8,
         'iran': 325,
         'governor': 94,
         'warning': 190,
         'that': 9314,
         'fall': 270,
         'sharply': 134,
         'jakarta': 160,
         'non': 84,
         'exporters': 41,
         'should': 425,
         'consider': 91,
         'increasing': 81,
         'output': 124,
         'cool': 77,
         'record': 843,
         'president': 1739,
         'purnomo': 16,
         'yusgiantoro': 16,
         'sunday': 1596,
         'washington': 1057,
         'auction': 125,
         'google': 484,
         'highly': 86,
         'anticipated': 85,
         'initial': 246,
         'public': 567,
         'offering': 379,
         'got': 295,
         'rocky': 18,
         'start': 563,
         'web': 579,
         'search': 481,
         'sidestepped': 2,
         'bullet': 8,
         'u': 2468,
         'securities': 241,
         'regulators': 209,
         'dollar': 378,
         'tumbled': 35,
         'broadly': 12,
         'data': 569,
         'showing': 139,
         'trade': 448,
         'deficit': 108,
         'june': 165,
         'cast': 44,
         'fresh': 229,
         'doubts': 52,
         'recovery': 122,
         'ability': 72,
         'draw': 121,
         'foreign': 477,
         'capital': 420,
         'fund': 287,
         'growing': 284,
         'gap': 58,
         'if': 983,
         'you': 945,
         'think': 138,
         'may': 1158,
         'need': 215,
         'help': 717,
         'your': 382,
         'elderly': 23,
         'relatives': 34,
         'with': 7609,
         'their': 3468,
         'finances': 25,
         'don': 173,
         't': 1390,
         'be': 3443,
         'shy': 26,
         'having': 171,
         'talk': 116,
         'purchasing': 11,
         'power': 453,
         'kids': 21,
         'big': 487,
         'why': 135,
         'school': 516,
         'season': 1088,
         'become': 333,
         'such': 397,
         'huge': 178,
         'marketing': 147,
         'phenomenon': 8,
         'there': 764,
         'little': 384,
         'cause': 119,
         'celebration': 37,
         'these': 194,
         'days': 617,
         'investors': 589,
         'value': 71,
         'focused': 59,
         'reason': 83,
         'feel': 64,
         'smug': 4,
         'only': 668,
         'because': 691,
         'they': 2105,
         've': 130,
         'lost': 355,
         'less': 331,
         'than': 2208,
         'folks': 13,
         'who': 1937,
         'stuck': 25,
         'growth': 566,
         'exploded': 111,
         '19': 281,
         '55': 42,
         '8bn': 9,
         'costs': 337,
         'drove': 113,
         'imports': 50,
         'according': 910,
         'figures': 144,
         'giant': 696,
         'shell': 74,
         'bracing': 14,
         'itself': 127,
         'takeover': 158,
         'attempt': 176,
         'possibly': 56,
         'french': 358,
         'rival': 327,
         'total': 117,
         'press': 375,
         'report': 705,
         'bidding': 44,
         'gets': 92,
         'underway': 28,
         'despite': 450,
         'minute': 106,
         'interview': 89,
         'bosses': 17,
         'playboy': 24,
         'magazine': 116,
         'show': 337,
         '12': 460,
         'eurozone': 17,
         'continues': 104,
         'grow': 91,
         'warnings': 79,
         'it': 6622,
         'slow': 144,
         'down': 902,
         'later': 230,
         'japan': 527,
         'slows': 7,
         'country': 924,
         'experiences': 10,
         'domestic': 120,
         'corporate': 243,
         'spending': 237,
         'interest': 362,
         'rates': 270,
         'trimmed': 17,
         '7': 893,
         '5': 1031,
         'south': 733,
         'african': 220,
         'central': 353,
         'bank': 812,
         'lack': 69,
         'hits': 164,
         'rand': 14,
         'surprises': 10,
         'cost': 316,
         'both': 399,
         'second': 1463,
         'hand': 167,
         'cars': 90,
         'five': 844,
         'years': 1346,
         'survey': 202,
         'found': 501,
         'korea': 387,
         'cuts': 197,
         'quarter': 888,
         'percentage': 36,
         'point': 213,
         '3': 1286,
         'bid': 419,
         'drive': 175,
         'shares': 733,
         'engine': 202,
         'floated': 19,
         'much': 554,
         '36bn': 1,
         'takes': 122,
         'place': 337,
         'hewlett': 108,
         'packard': 108,
         'disappointing': 89,
         'third': 1003,
         'profits': 246,
         'while': 818,
         'warns': 38,
         'final': 838,
         'will': 4377,
         'also': 437,
         'expectations': 202,
         'one': 2530,
         'oldest': 23,
         'textile': 9,
         'operators': 44,
         'indian': 169,
         'ocean': 56,
         'island': 194,
         'mauritius': 2,
         'shut': 92,
         'seven': 433,
         'factories': 52,
         'cut': 515,
         '900': 16,
         'jobs': 348,
         'chad': 39,
         'asks': 22,
         'imf': 24,
         'loan': 52,
         'pay': 462,
         'looking': 240,
         'more': 2671,
         '100': 364,
         'refugees': 55,
         'conflict': 112,
         'torn': 73,
         'darfur': 334,
         'western': 321,
         'sudan': 326,
         'running': 323,
         'japanese': 293,
         'nuclear': 506,
         'plant': 141,
         'hit': 783,
         'fatal': 21,
         'accident': 44,
         'close': 351,
         'reactors': 7,
         'safety': 144,
         'checks': 31,
         'trevor': 10,
         'baylis': 1,
         'veteran': 83,
         'inventor': 10,
         'famous': 60,
         'creating': 71,
         'freeplay': 1,
         'clockwork': 1,
         'radio': 184,
         'planning': 116,
         'float': 10,
         'saudi': 109,
         'arabia': 71,
         'ready': 158,
         'push': 155,
         'extra': 117,
         'into': 1922,
         'reverse': 20,
         'surging': 56,
         'led': 411,
         'uae': 5,
         'etisalat': 1,
         'plans': 792,
         'spend': 94,
         '1bn': 8,
         '544m': 1,
         'expansion': 99,
         'winning': 389,
         'two': 3356,
         'mobile': 631,
         'phone': 536,
         'licences': 2,
         'network': 693,
         'rail': 24,
         'flies': 18,
         'specialist': 31,
         'engineers': 53,
         'west': 559,
         'coast': 197,
         'mainline': 1,
         'uk': 386,
         'skills': 26,
         'shortage': 29,
         'bedford': 3,
         'scientists': 378,
         'nitromed': 1,
         'hope': 169,
         'experimental': 33,
         'drugs': 167,
         'cure': 9,
         'heart': 220,
         'disease': 86,
         'someday': 9,
         'lately': 22,
         'focus': 191,
         'been': 1830,
         'mundane': 3,
         'matters': 16,
         'i': 616,
         'submitted': 17,
         'buy': 446,
         'style': 90,
         'turn': 177,
         'out': 2040,
         'good': 337,
         'news': 875,
         'or': 1287,
         'bad': 125,
         'massachusetts': 81,
         'bargain': 26,
         'hunters': 21,
         'up': 2575,
         'droves': 2,
         'shopped': 1,
         'hard': 224,
         'yesterday': 1991,
         'tax': 239,
         'holiday': 92,
         'everything': 57,
         'treadmills': 1,
         'snow': 27,
         'blowers': 1,
         'candles': 4,
         'chandeliers': 2,
         'crediting': 1,
         'percent': 1271,
         'break': 125,
         'bringing': 90,
         'them': 706,
         'stores': 263,
         'e': 355,
         'mail': 246,
         'victim': 40,
         'own': 335,
         'success': 136,
         'conclusion': 23,
         'ibm': 485,
         'corp': 1713,
         'researchers': 253,
         'cambridge': 27,
         'spent': 139,
         'nearly': 510,
         'decade': 109,
         'conducting': 13,
         'field': 369,
         'tests': 90,
         'other': 945,
         'companies': 754,
         'how': 500,
         'employees': 183,
         'use': 397,
         'electronic': 163,
         'clear': 141,
         'internet': 1133,
         'killer': 23,
         'application': 145,
         'even': 565,
         'genius': 6,
         'mess': 9,
         'bill': 262,
         'gates': 56,
         'brilliant': 16,
         'technologist': 2,
         'he': 2698,
         'cofounded': 1,
         'microsoft': 1144,
         'guided': 13,
         'greatness': 7,
         'size': 256,
         'historical': 4,
         'consequence': 4,
         'blundered': 1,
         'terrorized': 3,
         'underlings': 1,
         'temper': 4,
         'parceled': 1,
         'praise': 15,
         'like': 605,
         'scrooge': 2,
         'gave': 250,
         'charity': 5,
         'lash': 6,
         'inspired': 38,
         'necessary': 37,
         'aggressiveness': 1,
         'beat': 460,
         'competition': 290,
         'thought': 144,
         'target': 767,
         'abusers': 1,
         'legal': 213,
         'weapons': 235,
         'we': 343,
         'all': 1314,
         'share': 390,
         'outrage': 8,
         'expressed': 77,
         'columnist': 23,
         'steve': 123,
         'bailey': 8,
         'sizzler': 1,
         'quot': 2743,
         'aug': 501,
         '11': 503,
         'killings': 20,
         'city': 1025,
         'poor': 137,
         'neighborhoods': 13,
         'no': 1323,
         'ignorance': 1,
         'argues': 9,
         'renewal': 7,
         'so': 628,
         'called': 470,
         'assault': 123,
         'weapon': 20,
         'ban': 133,
         'claiming': 68,
         'otherwise': 22,
         'uzis': 3,
         'ak': 6,
         '47s': 3,
         'flooding': 55,
         'streets': 83,
         'bush': 813,
         'saying': 347,
         'turned': 212,
         'corner': 17,
         'democratic': 213,
         'candidate': 106,
         'senator': 34,
         'john': 664,
         'f': 72,
         'kerry': 348,
         'wake': 89,
         'this': 2698,
         'month': 921,
         'quipped': 1,
         'marlborough': 4,
         'based': 682,
         'technology': 923,
         'suing': 24,
         'former': 979,
         'including': 571,
         'senior': 265,
         'managers': 99,
         'allegedly': 98,
         'conspiring': 23,
         'against': 1851,
         'working': 225,
         'opening': 312,
         'competing': 43,
         'business': 957,
         'square': 65,
         'lynn': 10,
         'brighter': 13,
         'sidewalks': 4,
         'curbs': 5,
         'fences': 5,
         'lights': 23,
         'landscaping': 2,
         'road': 155,
         'improvements': 44,
         'planned': 216,
         'gateway': 48,
         'artisan': 26,
         'block': 132,
         'key': 446,
         'area': 207,
         '830': 4,
         'state': 1067,
         'grant': 37,
         'given': 168,
         'lawsuit': 163,
         'gary': 79,
         'winnick': 4,
         'chief': 712,
         'global': 419,
         'crossing': 22,
         'refocuses': 2,
         'attention': 81,
         'what': 877,
         'mr': 71,
         'knew': 60,
         'imploded': 3,
         'russia': 544,
         'emerging': 56,
         'superpower': 3,
         'kevin': 109,
         'b': 370,
         'rollins': 3,
         'executive': 464,
         'talks': 592,
         'transitory': 2,
         'slip': 29,
         'customer': 102,
         'service': 944,
         'sees': 48,
         'broader': 32,
         'taking': 347,
         'cash': 307,
         'rich': 127,
         'people': 1538,
         'dying': 16,
         'wealth': 22,
         'stein': 3,
         'proposes': 7,
         'unique': 38,
         'solution': 79,
         'sell': 250,
         'titles': 55,
         'nobility': 1,
         'quality': 69,
         'distribution': 76,
         'hammered': 26,
         'reporting': 75,
         'large': 225,
         'loss': 365,
         'hurricane': 790,
         'charley': 146,
         'blows': 13,
         'house': 336,
         'make': 679,
         'results': 327,
         'not': 2026,
         'grim': 21,
         'tech': 217,
         'just': 904,
         'isn': 114,
         'tough': 107,
         'detroit': 168,
         'troubled': 131,
         'carmaker': 26,
         'thanks': 98,
         'maverick': 8,
         'designer': 25,
         'car': 373,
         'dazzling': 7,
         'hip': 27,
         'hop': 9,
         'crowd': 112,
         'americans': 331,
         'tricking': 3,
         'places': 45,
         'where': 494,
         'swim': 9,
         'here': 451,
         'look': 233,
         'wave': 68,
         'accessories': 6,
         '1993': 14,
         'six': 595,
         'geeks': 5,
         'had': 1717,
         'digital': 350,
         'nightmare': 34,
         'changed': 96,
         'culture': 21,
         'get': 574,
         'far': 283,
         'creepier': 2,
         'celebrity': 24,
         'fashion': 40,
         'booming': 30,
         'webpreneurs': 1,
         'recording': 40,
         'artist': 14,
         'channel': 74,
         'american': 921,
         'middle': 156,
         'class': 127,
         'tastes': 2,
         'quite': 72,
         'chip': 298,
         'davis': 166,
         'best': 356,
         'selling': 208,
         'problem': 129,
         'worry': 52,
         'find': 222,
         'every': 213,
         'specialized': 10,
         'today': 1376,
         'customers': 375,
         'increasingly': 99,
         'demanding': 61,
         'asia': 143,
         'elsewhere': 37,
         'henry': 42,
         'astorga': 1,
         'describes': 9,
         'complex': 61,
         'reality': 59,
         'faced': 93,
         'marketers': 7,
         'includes': 99,
         'used': 493,
         'want': 165,
         'performance': 263,
         'now': 712,
         'election': 465,
         'time': 1636,
         'republic': 133,
         'philippines': 51,
         'means': 85,
         'monkeys': 4,
         'rolling': 59,
         'around': 470,
         'those': 299,
         'political': 373,
         'fun': 30,
         'laughing': 8,
         'heads': 54,
         'strange': 29,
         'goings': 1,
         'characterize': 1,
         'process': 199,
         'loosely': 4,
         'model': 80,
         'de': 150,
         'facto': 5,
         'looks': 107,
         'fellini': 2,

In [12]:
len(counter)

38029

In [ ]:
len(counter.most_common(30000))
## most common method helps to filter the most occuring tokens for building vocab

30000

In [14]:
class Vocab:
  def __init__(self,counter,max_vocab_size):
    limited_counter = counter.most_common(max_vocab_size)

    self.idxTotoken=[]
    for token,freq in limited_counter:
      self.idxTotoken.append(token)

    self.idxTotoken.append('<pad>')
    self.idxTotoken.append('<unk>')

    self.tokenToidx = {}

    for idx,token in enumerate(self.idxTotoken):
      self.tokenToidx[token]=idx

    self.pad_token_idx = self.tokenToidx['<pad>']
    self.unk_token_idx = self.tokenToidx['<unk>']



  def encode(self,tokens):
    token_ids = []
    for token in tokens:
      token_id = self.tokenToidx.get(token,self.unk_token_idx)
      # if token in not part of vocab - use unk token_id for that token
      token_ids.append(token_id)

    return token_ids

In [15]:
vocab = Vocab(counter=counter,max_vocab_size=30000)

In [16]:
text = 'Paris is capital of France'
tokens = tokenize(text)
print(tokens)

['paris', 'is', 'capital', 'of', 'france']

In [17]:
token_ids = vocab.encode(tokens)
print(token_ids)

[800, 17, 406, 3, 770]

In [23]:
from torch.utils.data import Dataset,DataLoader
from torch.nn.utils.rnn import pad_sequence,pack_padded_sequence
import torch

In [37]:
class TextDataset(Dataset):
  def __init__(self,texts,labels,vocab,max_len=256):
    self.vocab=vocab
    self.max_len=max_len
    self.datapoints = []
    for text,label in zip(texts,labels):
      tokens = tokenize(text)[:self.max_len] #truncation
      token_ids = self.vocab.encode(tokens)
      self.datapoints.append((torch.tensor(token_ids,dtype=torch.long),label))

  def __len__(self):
    return len(self.datapoints)

  # this function is needed for working with indexing
  def __getitem__(self,idx):
    return self.datapoints[idx]



# applying padding for batches
# converting data into torch tensors
def collate_fn(pad_index:int):
  def collate(batch):
    sequences,labels = zip(*batch)
    lengths = torch.tensor([len(s) for s in sequences],dtype=torch.long)
    padded = pad_sequence(sequences,batch_first=True,padding_value=pad_index)
    labels = torch.tensor(labels,dtype=torch.long)
    return padded,lengths,labels
  return collate


# torch.tensor -> matrix datatypes in torch
# We are converting all matrixes in torch.long -> which is a float datatype in torch
# All matrixes need to be in same datatype for correct operations



## Why padding is needed ?
'''
text 1 : This is a great place
-> this is a great place
token_ids : t0 t1 t2 t3 t4

--padding
text 2 : Hello all
-> hello all <pad> <pad> <pad>
token_ids : t0 t1 t2 t3 t4


--truncation
text 3 : There is a very big waterfall
-> there is a very big
token_ids : t0 t1 t2 t3 t4

Now as the number of token ids are matching, these two texts can be passed in a single batch matrix
'''

'\ntext 1 : This is a great place\n-> this is a great place\ntoken_ids : t0 t1 t2 t3 t4\n\n--padding\ntext 2 : Hello all \n-> hello all <pad> <pad> <pad>\ntoken_ids : t0 t1 t2 t3 t4\n\n\n--truncation\ntext 3 : There is a very big waterfall\n-> there is a very big\ntoken_ids : t0 t1 t2 t3 t4\n\nNow as the number of token ids are matching, these two texts can be passed in a single batch matrix\n'

In [27]:
vocab.unk_token_idx

30001

## RNN Model Architecture

In [29]:
from torch import nn

class RNNTextClf(nn.Module):
  def __init__(self,vocab_size,embed_dim,hidden_dim,num_classes,pad_idx,num_layers=1,
               dropout=0.3):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,embed_dim,padding_idx=pad_idx)
    self.lstm = nn.LSTM(
        input_size = embed_dim,
        hidden_size = hidden_dim, # number of nodes in LSTM layer
        batch_first = True,
        bidirectional = True,
        num_layers = num_layers,
        dropout = dropout if num_layers>1 else 0.0
    )
    self.dropout = nn.Dropout(dropout)

    # classification head - output layer
    self.clf_head = nn.Linear(in_features= hidden_dim*2, # *2 is due to bidirectional nature
                              out_features=num_classes)


  def forward(self,batch,lengths):
    # batch : (batch_size,seq_lengths)
    embedded = self.embedding(batch)
    embedded = self.dropout(embedded)

    packed = pack_padded_sequence(
        embedded,lengths,batch_first=True,enforce_sorted=False
    )
    _,(hidden,_) = self.lstm(packed)

    # hidden : num_layers*2(bidirectional) x batch_size x hidden_dim
    # hidden[-2] : left to right context vector
    # hidden[-1] : right to left context vector
    concat_hidden = torch.concat((hidden[-2],hidden[-1]),dim=1)
    concate_hidden = self.dropout(concat_hidden)
    return self.clf_head(concat_hidden)

In [35]:
criterion = nn.CrossEntropyLoss()
## this is two in one loss function , which applies softmax on given inputs and then computes loss wrt labels
## Due to this we don't need a dedicated softmax activation in last layer of model

def run_epoch(model,loader,criterion,device,optimizer):
  model.train()
  total_loss = 0
  with torch.set_grad_enabled(True):
    for i ,(padded,lengths,labels) in enumerate(loader):
      output = model(padded,lengths)
      loss = criterion(output,labels)
      # CELoss will first apply softmax on output and then compute loss wrt labels

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      total_loss+=loss.item()

      print(f"Batch : {i}\n Batch Loss : {loss.item()}\n Total Epoch Loss : {total_loss}")

In [36]:
test_df = pd.read_csv('/content/drive/MyDrive/MLDatasets/text_classification/test_2k.csv',names=['label','heading','text'])
test_df.head()

,label,heading,text
0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...
1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o..."
2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...
3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...
4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...

In [39]:
train_df.isna().sum()

label      0
heading    0
text       0
dtype: int64

In [42]:
train_df['text']=train_df['text'].apply(lambda x:x.strip())
train_df[train_df['text']=='']

Empty DataFrame
Columns: [label, heading, text]
Index: []

In [43]:
train_texts = train_df['text'].to_list()
train_labels = train_df['label'].to_list()

In [44]:
test_df['text']=test_df['text'].apply(lambda x:x.strip())
test_df[test_df['text']=='']

Empty DataFrame
Columns: [label, heading, text]
Index: []

In [45]:
test_texts = test_df['text'].to_list()
test_labels = test_df['label'].to_list()

In [51]:
## Create datasets
MAX_LEN=256
train_ds = TextDataset(train_texts,train_labels,vocab,max_len=MAX_LEN)
test_ds = TextDataset(test_texts,test_labels,vocab,max_len=MAX_LEN)

collate = collate_fn(vocab.pad_token_idx)

In [48]:
train_ds[100]

(tensor([  298,   101,     1,  3714,   513,  1214,     2,  8461,  6214,     5,
         19384,   222,  1655,     2,    30,   167,     2,  3059,   708,     0,
         19385,  3060,    34,  1727,    57,  7024,     5,    89,    30,    12,
          2066,    12, 24457,    19,  9482,  3404]),
 4)

In [52]:
BATCH_SIZE = 64
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,shuffle =True,collate_fn = collate)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE,shuffle =True,collate_fn = collate)

In [67]:
batch = next(iter(train_loader))

In [68]:
# token_ids
batch[0].shape

torch.Size([64, 79])

In [60]:
batch[0]

tensor([[   35,    16,    25,  ..., 30000, 30000, 30000],
        [   16,   115,    30,  ..., 30000, 30000, 30000],
        [  130,     0,  1813,  ..., 30000, 30000, 30000],
        ...,
        [    1, 23823,   468,  ..., 30000, 30000, 30000],
        [  200,   301,    22,  ..., 30000, 30000, 30000],
        [ 1431,  1155,   659,  ..., 30000, 30000, 30000]])

In [58]:
# labels
batch[1].shape

torch.Size([64])